### ISSUE TITLE
bsTimpicker $apply already in progress error with click

### ISSUE THREAD

**Issue by LPCmedia** [mgcrea/angular-strap#1329]
**Using the bs-timepicker with data-arrow-behavior="picker" click the arrows creates an Error: [$rootScope:inprog] $apply with  already in progress AngularJS v1.3.2. removing the attibute eliminated the error.**

`<input
                                        id="eventEndTime" name="eventEndTime"
                                        data-placement="bottom-left" size="8" type="text"
                                        data-min-time="{{vm.event.eventDate}}" 
                                        data-iconup="fa fa-chevron-circle-up"
                                        data-icondown="fa fa-chevron-circle-down"
                                        data-length="1"
                                        data-minute-step="15"
                                        data-arrow-behavior="picker"
                                        data-autoclose="true"
                                        data-timeformat="shortTime"
                                        data-ng-model="vm.event.eventEndDateTime"
                                        data-ng-required=""
                                        class="form-control"
                                        placeholder="Event Start"
                                        data-bs-timepicker="">`

**Full stack trace**

```Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.2/$rootScope/inprog?p0=%24apply
    at REGEX_STRING_REGEXP (http://jetadmin.devbox.com/scripts/angular.js:80:12)
    at beginPhase (http://jetadmin.devbox.com/scripts/angular.js:14553:15)
    at Scope.$get.Scope.$digest (http://jetadmin.devbox.com/scripts/angular.js:13996:9)
    at Object.angular.module.provider.$get.$timepicker.$setTimeByStep (http://jetadmin.devbox.com/scripts/angular-strap.js:3442:23)
    at Scope.angular.module.provider.$get.scope.$arrowAction (http://jetadmin.devbox.com/scripts/angular-strap.js:3425:25)
    at $parseFunctionCall (http://jetadmin.devbox.com/scripts/angular.js:12158:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://jetadmin.devbox.com/scripts/angular.js:22645:17)
    at Scope.$get.Scope.$eval (http://jetadmin.devbox.com/scripts/angular.js:14200:28)
    at Scope.$get.Scope.$apply (http://jetadmin.devbox.com/scripts/angular.js:14298:23)
    at HTMLButtonElement.<anonymous> (http://jetadmin.devbox.com/scripts/angular.js:22650:23)```

**Comment by risinglf** [comment]
Fixed in 2.1.5 (for me)
