### ISSUE TITLE
Error: [$sce:unsafe] http://errors.angularjs.org/1.3.5/$sce/unsafe

### ISSUE THREAD

**Issue by dgrene** [mgcrea/angular-strap#1368]
Error: [$sce:unsafe] http://errors.angularjs.org/1.3.5/$sce/unsafe
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:6:416
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:130:470)
    at getTrusted (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:132:207)
    at Object.d.(anonymous function) [as getTrustedHtml] (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:133:406)
    at Object.fn (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:226:213)
    at k.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js:122:459)
    at safeDigest (http://mgcrea.github.io/angular-strap/dist/angular-strap.js:2461:72)
    at Object.ModalFactory.$modal.show (http://mgcrea.github.io/angular-strap/dist/angular-strap.js:2364:11)
    at HTMLButtonElement.ModalFactory.$modal.toggle (http://mgcrea.github.io/angular-strap/dist/angular-strap.js:2428:51) undefinedangular.js:11500 (anonymous function)angular.js:8479 (anonymous function)angular-block-ui.js:22 (anonymous function)angular.js:14151 k.$digestangular-strap.js:2461 safeDigestangular-strap.js:2364 ModalFactory.$modal.showangular-strap.js:2428 ModalFactory.$modal.toggleangular.js:2992 c

getting this error while implementing aside

**Comment by vmlf01** [comment]
see #1598
