### ISSUE TITLE
TypeError: a.replace is not a function

### ISSUE THREAD

**Issue by blacksmoke26** [mgcrea/angular-strap#1725]
Used:
```javascript
var myPopover = $popover(angular.element('#locale-zipFind'), {title: 'My Title', content: 'My Content', trigger: 'manual'});
```
Occurred:
```
TypeError: a.replace is not a function
    at a (http://domain.dev/core/libs/angular-bootstrap/ui-bootstrap-tpls.min.js:9:743)
    at $get (http://domain.dev/core/libs/angular-bootstrap/ui-bootstrap-tpls.min.js:9:1232)
    at n (http://domain.dev/core/libs/angular-strap/dist/angular-strap.min.js:9:8183)
    at Object.$get (http://domain.dev/core/ng-common.js:429:19)
    at Object.d [as invoke] (http://domain.dev/core/libs/angular/angular.min.js:35:36)
    at http://domain.dev/core/libs/angular/angular.min.js:36:288
    at c (http://domain.dev/core/libs/angular/angular.min.js:34:305)
    at d (http://domain.dev/core/libs/angular/angular.min.js:35:6)
    at Object.instantiate (http://domain.dev/core/libs/angular/angular.min.js:35:165)
    at $get (http://domain.dev/core/libs/angular/angular.min.js:67:421) <div ng-view="" class="ng-scope">
```

**Comment by vmlf01** [comment]
This looks like a conflict between Angular Strap and ui-bootstrap. Have a look at https://github.com/mgcrea/angular-strap/issues/521 for more info.
