### ISSUE TITLE
error with modal

### ISSUE THREAD

**Issue by marfanjr** [mgcrea/angular-strap#1793]
i don't know what's happening. when i tried to show a modal, i've got this error:

```
TypeError: Cannot read property 'defaultPrevented' of undefined
    at Object.ModalFactory.$modal.show (http://localhost:9001/bower_components/angular-strap/dist/angular-strap.js:1951:72)
    at http://localhost:9001/scripts/controllers/configurations/students/manage.js:648:27
    at processQueue (http://localhost:9001/bower_components/angular/angular.js:14567:28)
    at http://localhost:9001/bower_components/angular/angular.js:14583:27
    at Scope.$eval (http://localhost:9001/bower_components/angular/angular.js:15846:28)
    at Scope.$digest (http://localhost:9001/bower_components/angular/angular.js:15657:31)
    at Scope.$apply (http://localhost:9001/bower_components/angular/angular.js:15951:24)
    at done (http://localhost:9001/bower_components/angular/angular.js:10364:47)
    at completeRequest (http://localhost:9001/bower_components/angular/angular.js:10536:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9001/bower_components/angular/angular.js:10477:9)
```

my code:

```
var modal;
var sayCheese;
$scope.captureImageFromWebcam = function () {
    modal = $modal({
        scope: $scope,
        template: 'views/modal.capture.image.tpl.html',
        title: 'Capturar Imagem',
        show: false,
        placement: 'center',
        container: 'body',
        backdrop: 'static'
    });
    modal.$promise.then(function () {
        modal.show();
        sayCheese = new SayCheese('#webcam', {audio: false});
        sayCheese.on('snapshot', function (snapshot) {
            sayCheese.stop();
            $scope.hideModal(snapshot);
        });
        sayCheese.on('error', function () {
            $scope.webcamError = true;
            sayCheese.stop();
        });
        sayCheese.start();
    });
};
```

**Comment by vmlf01** [comment]
Do you still have this problem? I have put your code, except for the sayCheese bit, in a plunker and it seems to work:
http://plnkr.co/edit/ANT9c4FVhZEr7Loh4aZk?p=preview

Maybe it is something related to the modal template you are using?
