### ISSUE TITLE
Can't build stuff...

### ISSUE THREAD

**Issue by lookfirst** [mgcrea/angular-strap#1954]
Node 5.0.0
npm 3.x

npm install wouldn't finish (weird connection reset errors) so I reverted to npm 2.x and I was able to install. Now when I try to run gulp...

```
gulp
[14:14:42] Found 1 undertaker-registry to load with ng-factory
Error: Cannot find module 'graceful-fs'
/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:30
      taker.registry(new (tasks[task])(taker));
                     ^

TypeError: tasks[task] is not a function
    at /Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:30:22
    at Array.forEach (native)
    at /Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:29:24
    at Array.forEach (native)
    at Object.exports.registerTasks (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:27:14)
    at ngFactory (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/index.js:30:16)
    at Function.ngFactory.use (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/index.js:60:37)
    at Object.<anonymous> (/Users/jon/checkout/angular-strap/gulpfile.js:6:36)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by mgcrea** [comment]
Try `$(npm bin)/gulp build`

**Comment by lookfirst** [comment]
@mgcrea Dude... wtf closing without even waiting for a response?

I did do that... 

```
angular-strap $ which gulp
./node_modules/.bin/gulp
```

I also don't have gulp installed globally for exactly this reason.

```
dir /usr/local/lib/node_modules/
total 0
0 drwxr-xr-x    7 jon  admin   238 Nov 11 13:56 ./
0 drwxrwxr-x  179 jon  admin  6086 Nov 10 21:26 ../
0 drwxr-xr-x    3 jon  admin   102 Nov 10 21:45 .bin/
0 drwxr-xr-x   10 jon  admin   340 Nov  5 15:22 bower/
0 drwxr-xr-x   11 jon  admin   374 Apr 26  2015 fsls/
0 drwxr-xr-x   25 jon  admin   850 Nov 11 13:56 npm/
0 drwxr-xr-x   14 jon  admin   476 Nov 10 21:45 npm-check-updates/
```

**Comment by lookfirst** [comment]
```
$(npm bin)/gulp build
[15:50:38] Found 1 undertaker-registry to load with ng-factory
Error: Cannot find module 'graceful-fs'
/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:30
      taker.registry(new (tasks[task])(taker));
                     ^

TypeError: tasks[task] is not a function
    at /Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:30:22
    at Array.forEach (native)
    at /Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:29:24
    at Array.forEach (native)
    at Object.exports.registerTasks (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/tasks.js:27:14)
    at ngFactory (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/index.js:30:16)
    at Function.ngFactory.use (/Users/jon/checkout/angular-strap/node_modules/ng-factory/lib/index.js:60:37)
    at Object.<anonymous> (/Users/jon/checkout/angular-strap/gulpfile.js:6:36)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by mgcrea** [comment]
Your NPM install is broken, and it's not an issue with AngularStrap.
You could try `npm cache clean; rm -rf node_modules; npm i`.

**Comment by lookfirst** [comment]
I've done all that... sigh...

It is a fresh npm install. Everything else works fine on my system including my own complicated gulp 3x build system. Your project is the only thing failing.

**Comment by lookfirst** [comment]
Also, looking in travis at the latest build, the npm install is pretty bad; nan fails to compile and karma reports errors which doesn't kill the build...

**Comment by mgcrea** [comment]
```
λ /tmp
$ git clone -o github git@github.com:mgcrea/angular-strap.git
Cloning into 'angular-strap'...
remote: Counting objects: 12168, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 12168 (delta 11), reused 0 (delta 0), pack-reused 12142
Receiving objects: 100% (12168/12168), 8.24 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (7454/7454), done.
Checking connectivity... done.
λ /tmp
$ cd angular-strap/
λ /tmp/angular-strap @master
$ npm i
 
> phantomjs@1.9.18 install /private/tmp/angular-strap/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/3c/hlvq7lf55wl9f28g153_775r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
/ [================------------------------] 39% 0.0s/
Received 9187K total.
Extracting zip contents
Removing /private/tmp/angular-strap/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/3c/hlvq7lf55wl9f28g153_775r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1447286373745/phantomjs-1.9.8-macosx -> /private/tmp/angular-strap/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /private/tmp/angular-strap/node_modules/phantomjs/lib/phantom/bin/phantomjs
 
> utf-8-validate@1.2.1 install /private/tmp/angular-strap/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.2.1 install /private/tmp/angular-strap/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> utf-8-validate@1.2.1 install /private/tmp/angular-strap/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.2.1 install /private/tmp/angular-strap/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> sauce-connect-launcher@0.13.0 postinstall /private/tmp/angular-strap/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher
> node scripts/install.js

 
> fsevents@1.0.5 install /private/tmp/angular-strap/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/private/tmp/angular-strap/node_modules/karma/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
 
> fsevents@1.0.5 install /private/tmp/angular-strap/node_modules/gulp-pre/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/private/tmp/angular-strap/node_modules/gulp-pre/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
 
> gulp-pre@4.0.0-alpha.4 postinstall /private/tmp/angular-strap/node_modules/gulp-pre
> ln -sfv gulp-pre ./../gulp

‘./../gulp’ -> ‘gulp-pre’
 
> utf-8-validate@1.2.1 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.2.1 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> bufferutil@1.2.1 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> utf-8-validate@1.2.1 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> spawn-sync@1.0.14 postinstall /private/tmp/angular-strap/node_modules/factory-angular-channels/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

 
> node-sass@3.4.1 install /private/tmp/angular-strap/node_modules/factory-angular-channels/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /private/tmp/angular-strap/node_modules/factory-angular-channels/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node
 
> node-sass@3.4.1 postinstall /private/tmp/angular-strap/node_modules/factory-angular-channels/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /private/tmp/angular-strap/node_modules/factory-angular-channels/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
\
> fsevents@1.0.2 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote

> fsevents@1.0.2 install /private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/private/tmp/angular-strap/node_modules/undertaker-lib-tasks/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote

> gulp-pre@4.0.0-alpha.4 postinstall /private/tmp/angular-strap/node_modules/gulp
> ln -sfv gulp-pre ./../gulp

‘./../gulp/gulp-pre’ -> ‘gulp-pre’
gulp-rename@1.2.2 node_modules/gulp-rename

karma-jasmine@0.3.6 node_modules/karma-jasmine

eslint-config-airbnb@0.1.1 node_modules/eslint-config-airbnb

jasmine-core@2.3.4 node_modules/jasmine-core

karma-chrome-launcher@0.2.1 node_modules/karma-chrome-launcher
├── fs-access@1.0.0 (null-check@1.0.0)
└── which@1.2.0 (is-absolute@0.1.7)

jshint-stylish@2.0.1 node_modules/jshint-stylish
├── plur@1.0.0
├── log-symbols@1.0.2
├── text-table@0.2.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
└── string-length@1.0.1 (strip-ansi@3.0.0)

through2@2.0.0 node_modules/through2
├── xtend@4.0.1
└── readable-stream@2.0.4 (string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.1, inherits@2.0.1, process-nextick-args@1.0.3, util-deprecate@1.0.2)

del@2.0.2 node_modules/del
├── is-path-cwd@1.0.0
├── pify@2.3.0
├── object-assign@4.0.1
├── pinkie-promise@1.0.0 (pinkie@1.0.0)
├── is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
├── globby@3.0.1 (arrify@1.0.0, array-union@1.0.1, glob@5.0.15)
└── rimraf@2.4.3 (glob@5.0.15)

codeclimate-test-reporter@0.1.1 node_modules/codeclimate-test-reporter
├── async@0.7.0
├── lcov-parse@0.0.6
└── request@2.34.0 (aws-sign2@0.5.0, tunnel-agent@0.3.0, forever-agent@0.5.2, qs@0.6.6, oauth-sign@0.3.0, mime@1.2.11, json-stringify-safe@5.0.1, tough-cookie@2.2.0, node-uuid@1.4.3, http-signature@0.10.1, form-data@0.1.4, hawk@1.0.0)

gulp-ng-annotate@1.1.0 node_modules/gulp-ng-annotate
├── merge@1.2.0
├── bufferstreams@0.0.2 (readable-stream@1.1.13)
├── through2@0.4.2 (readable-stream@1.0.33, xtend@2.1.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── ng-annotate@1.0.2 (tryor@0.1.2, stringmap@0.2.2, stringset@0.2.1, simple-is@0.2.0, alter@0.2.0, simple-fmt@0.1.0, stable@0.1.5, convert-source-map@1.0.0, ordered-ast-traverse@1.1.1, source-map@0.4.4, acorn@2.1.0, optimist@0.6.1)

gulp-util@3.0.7 node_modules/gulp-util
├── array-differ@1.0.0
├── array-uniq@1.0.2
├── beeper@1.1.0
├── lodash._reinterpolate@3.0.0
├── lodash._reescape@3.0.0
├── fancy-log@1.1.0
├── object-assign@3.0.0
├── lodash._reevaluate@3.0.0
├── replace-ext@0.0.1
├── minimist@1.2.0
├── has-gulplog@0.1.0 (sparkles@1.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── vinyl@0.5.3 (clone-stats@0.0.1, clone@1.0.2)
├── gulplog@1.0.0 (glogg@1.0.0)
├── lodash.template@3.6.2 (lodash._basetostring@3.0.1, lodash.templatesettings@3.1.0, lodash._basecopy@3.0.1, lodash.escape@3.0.0, lodash._isiterateecall@3.0.9, lodash.restparam@3.6.1, lodash._basevalues@3.0.0, lodash.keys@3.1.2)
├── multipipe@0.1.2 (duplexer2@0.0.2)
└── dateformat@1.0.11 (get-stdin@5.0.1, meow@3.5.0)

gulp-uglify@1.4.2 node_modules/gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── isobject@2.0.0 (isarray@0.0.1)
├── vinyl-sourcemaps-apply@0.2.0 (source-map@0.5.3)
├── uglify-js@2.5.0 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.3, yargs@3.5.4)
└── fancy-log@1.1.0 (chalk@1.1.1, dateformat@1.0.11)

phantomjs@1.9.18 node_modules/phantomjs
├── which@1.0.9
├── progress@1.1.8
├── kew@0.4.0
├── adm-zip@0.4.4
├── request-progress@0.3.1 (throttleit@0.0.2)
├── request@2.42.0 (aws-sign2@0.5.0, forever-agent@0.5.2, caseless@0.6.0, tunnel-agent@0.4.1, oauth-sign@0.4.0, stringstream@0.0.5, json-stringify-safe@5.0.1, tough-cookie@2.2.0, mime-types@1.0.2, qs@1.2.2, node-uuid@1.4.3, http-signature@0.10.1, bl@0.9.4, form-data@0.1.4, hawk@1.1.1)
├── npmconf@2.1.1 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.2, semver@4.3.6, nopt@3.0.4, osenv@0.1.3, config-chain@1.1.9, mkdirp@0.5.1)
└── fs-extra@0.23.1 (path-is-absolute@1.0.0, jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.3)

karma-phantomjs-launcher@0.2.1 node_modules/karma-phantomjs-launcher
└── lodash@3.10.1

gulp-jshint@1.12.0 node_modules/gulp-jshint
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
├── lodash@3.10.1
└── jshint@2.8.0 (strip-json-comments@1.0.4, exit@0.1.2, console-browserify@1.1.0, shelljs@0.3.0, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)

karma-sauce-launcher@0.3.0 node_modules/karma-sauce-launcher
├── q@1.4.1
├── saucelabs@1.0.1 (https-proxy-agent@1.0.0)
├── sauce-connect-launcher@0.13.0 (async@1.4.0, adm-zip@0.4.7, rimraf@2.4.3, lodash@3.10.1)
└── wd@0.3.12 (vargs@0.1.0, async@1.0.0, underscore.string@3.0.3, request@2.55.0, archiver@0.14.4, lodash@3.9.3)

karma-coverage@0.5.3 node_modules/karma-coverage
├── source-map@0.5.3
├── minimatch@3.0.0 (brace-expansion@1.1.1)
├── dateformat@1.0.11 (get-stdin@5.0.1, meow@3.5.0)
└── istanbul@0.4.0 (abbrev@1.0.7, async@1.5.0, wordwrap@1.0.0, nopt@3.0.4, esprima@2.5.0, once@1.3.2, supports-color@3.1.2, which@1.2.0, mkdirp@0.5.1, fileset@0.2.1, resolve@1.1.6, escodegen@1.7.0, handlebars@4.0.4, js-yaml@3.4.3)

eslint@1.9.0 node_modules/eslint
├── to-double-quotes@2.0.0
├── escape-string-regexp@1.0.3
├── to-single-quotes@2.0.0
├── object-assign@4.0.1
├── path-is-absolute@1.0.0
├── path-is-inside@1.0.1
├── globals@8.11.0
├── xml-escape@1.0.0
├── estraverse@4.1.1
├── strip-json-comments@1.0.4
├── esutils@2.0.2
├── estraverse-fb@1.3.1
├── text-table@0.2.0
├── espree@2.2.5
├── debug@2.2.0 (ms@0.7.1)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── is-resolvable@1.0.0 (tryit@1.0.2)
├── optionator@0.6.0 (fast-levenshtein@1.0.7, type-check@0.3.1, levn@0.2.5, wordwrap@0.0.3, deep-is@0.1.3, prelude-ls@1.1.2)
├── json-stable-stringify@1.0.0 (jsonify@0.0.0)
├── glob@5.0.15 (inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@3.0.0 (brace-expansion@1.1.1)
├── shelljs@0.5.3
├── doctrine@0.7.0 (isarray@0.0.1, esutils@1.1.6)
├── chalk@1.1.1 (supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── lodash.merge@3.3.2 (lodash._getnative@3.9.1, lodash.keys@3.1.2, lodash._arraycopy@3.0.0, lodash.keysin@3.0.8, lodash.isarray@3.0.4, lodash.isarguments@3.0.4, lodash.istypedarray@3.0.2, lodash._arrayeach@3.0.0, lodash.isplainobject@3.2.0, lodash._createassigner@3.1.1, lodash.toplainobject@3.0.0)
├── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── file-entry-cache@1.2.4 (flat-cache@1.0.10)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.4)
├── lodash.omit@3.1.0 (lodash.restparam@3.6.1, lodash._pickbyarray@3.0.2, lodash._bindcallback@3.0.1, lodash._arraymap@3.0.0, lodash._baseflatten@3.1.4, lodash.keysin@3.0.8, lodash._pickbycallback@3.0.0, lodash._basedifference@3.0.3)
├── is-my-json-valid@2.12.3 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
├── handlebars@4.0.4 (async@1.5.0, source-map@0.4.4, optimist@0.6.1, uglify-js@2.4.24)
├── inquirer@0.11.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, ansi-escapes@1.1.0, figures@1.4.0, cli-width@1.1.0, rx-lite@3.1.2, through@2.3.8, run-async@0.1.0, readline2@1.0.1, cli-cursor@1.0.2, lodash@3.10.1)
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
└── escope@3.2.0 (esrecurse@3.1.1, estraverse@3.1.0, es6-map@0.1.2, es6-weak-map@0.1.4)

karma@0.13.15 node_modules/karma
├── rimraf@2.4.3
├── batch@0.5.3
├── graceful-fs@4.1.2
├── di@0.0.1
├── mime@1.3.4
├── colors@1.1.2
├── source-map@0.5.3
├── http-proxy@1.12.0 (eventemitter3@1.1.1, requires-port@0.0.1)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@3.0.0 (brace-expansion@1.1.1)
├── dom-serialize@2.2.1 (custom-event@1.0.0, void-elements@2.0.1, extend@3.0.0, ent@2.2.0)
├── useragent@2.1.7 (lru-cache@2.2.4)
├── bluebird@2.10.2
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
├── body-parser@1.14.1 (content-type@1.0.1, bytes@2.1.0, depd@1.1.0, qs@5.1.0, raw-body@2.1.4, on-finished@2.3.0, http-errors@1.3.1, debug@2.2.0, iconv-lite@0.4.12, type-is@1.6.9)
├── expand-braces@0.1.2 (array-unique@0.2.1, array-slice@0.2.3, braces@0.1.5)
├── log4js@0.6.27 (async@0.2.10, underscore@1.8.2, semver@4.3.6, readable-stream@1.0.33)
├── lodash@3.10.1
├── socket.io@1.3.7 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.4, socket.io-client@1.3.7)
├── core-js@1.2.6
└── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, async-each@0.1.6, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0, fsevents@1.0.5)

gulp-pre@4.0.0-alpha.4 node_modules/gulp-pre
├── vinyl-fs@2.2.1 (is-valid-glob@0.3.0, object-assign@4.0.1, graceful-fs@4.1.2, strip-bom-stream@1.0.0, through2-filter@2.0.0, strip-bom@2.0.0, vinyl@1.1.0, gulp-sourcemaps@1.6.0, merge-stream@1.0.0, mkdirp@0.5.1, duplexify@3.4.2, glob-stream@5.2.0)
├── gulp-cli@0.4.0 (mute-stdout@0.1.0, interpret@0.6.6, pretty-hrtime@1.0.1, archy@1.0.0, tildify@1.1.2, v8flags@2.0.10, chalk@1.1.1, gulplog@1.0.0, wreck@6.3.0, semver-greatest-satisfied-range@1.0.0, yargs@3.29.0, liftoff@2.2.0, matchdep@1.0.0, fancy-log@1.1.0)
├── undertaker@0.12.1 (undertaker-registry@0.0.3, last-run@1.1.0, bach@0.4.1, lodash@3.10.1, es6-weak-map@1.0.2)
└── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-glob@2.0.1, is-binary-path@1.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0, fsevents@1.0.5)

ng-factory@1.1.0 node_modules/ng-factory
├── undertaker-registry@0.0.3
├── tildify@1.1.2 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── cwd@0.8.4 (lazy-cache@0.2.4, look-up@0.8.1)
├── ng-cli@0.7.0 (commander@2.9.0, export-files@2.1.0, resolve-require@0.2.0, cwd@0.6.0, load-pkg@1.3.0)
├── resolve-dep@0.5.3 (load-pkg@0.1.0, lodash@2.4.2, arrayify-compact@0.1.0, lookup-path@0.3.0, resolve@1.1.6, multimatch@0.3.0, globby@0.1.1, cwd@0.3.7)
├── lodash@3.10.1
└── undertaker@0.12.1 (last-run@1.1.0, bach@0.4.1, es6-weak-map@1.0.2)

factory-angular-channels@0.9.0 node_modules/factory-angular-channels
├── merge2@0.3.6
├── gulp-changed@1.3.0
├── require-dir@0.3.0
├── sort-stream@1.0.1 (through@2.3.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── gulp-sourcemaps@1.6.0 (graceful-fs@4.1.2, convert-source-map@1.1.1, strip-bom@2.0.0, vinyl@1.1.0)
├── merge-stream@1.0.0 (readable-stream@2.0.3)
├── stream-combiner2@1.1.1 (duplexer2@0.1.2, readable-stream@2.0.3)
├── gulp-match@1.0.0 (minimatch@3.0.0)
├── gulp-inject@3.0.0 (event-stream@3.3.2)
├── gulp-concat-util@0.5.4 (lodash.assign@3.2.0, concat-with-sourcemaps@1.0.4)
├── gulp-angular-filesort@1.1.1 (toposort@0.2.12, event-stream@3.3.2, ng-dependencies@0.2.0)
├── vinyl-fs@2.2.1 (is-valid-glob@0.3.0, object-assign@4.0.1, graceful-fs@4.1.2, strip-bom-stream@1.0.0, strip-bom@2.0.0, through2-filter@2.0.0, vinyl@1.1.0, mkdirp@0.5.1, duplexify@3.4.2, glob-stream@5.0.0)
├── gulp-size@2.0.0 (stream-counter@1.0.0, gzip-size@3.0.0, pretty-bytes@2.0.1)
├── resolve-require@0.2.0 (tildify@1.1.2, resolve@1.1.6, cwd@0.6.0)
├── gulp-htmlmin@1.2.0 (object-assign@4.0.1, tryit@1.0.2, bufferstreams@1.1.0, readable-stream@2.0.3, html-minifier@0.8.0)
├── gulp-cleancss@0.2.2 (chalk@0.4.0, clean-css@2.2.23, through2@0.5.1, gulp-util@2.2.17)
├── gulp-ngtemplate@0.2.5 (chalk@0.4.0, through2@0.5.1, gulp-util@2.2.20)
├── main-bower-files@2.9.0 (path-exists@1.0.0, strip-json-comments@1.0.4, extend@2.0.1, multimatch@2.0.0, globby@2.1.0, vinyl-fs@1.0.0)
├── gulp-nginclude@0.4.7 (lodash.assign@3.2.0, glob@5.0.15, cheerio@0.19.0)
├── gulp-jade@1.1.0 (jade@1.11.0)
├── lodash@3.10.1
├── gulp-sass@2.1.0 (object-assign@4.0.1, vinyl-sourcemaps-apply@0.2.0, node-sass@3.4.1)
├── gulp-if@2.0.0 (ternary-stream@2.0.0)
├── gulp-autoprefixer@3.1.0 (vinyl-sourcemaps-apply@0.2.0, postcss@5.0.10, autoprefixer@6.0.3)
├── gulp-less@3.0.3 (object-assign@2.1.1, through2@0.6.5, vinyl-sourcemaps-apply@0.1.4, accord@0.15.2, less@2.5.3)
├── gulp-babel@6.0.0 (object-assign@4.0.1, replace-ext@0.0.1, vinyl-sourcemaps-apply@0.2.0, babel-core@6.0.14)
└── babel-preset-es2015@6.0.14 (babel-plugin-transform-es2015-block-scoped-functions@6.0.14, babel-plugin-transform-es2015-for-of@6.0.14, babel-plugin-transform-es2015-constants@6.0.14, babel-plugin-transform-es2015-destructuring@6.0.14, babel-plugin-transform-es2015-template-literals@6.0.14, babel-plugin-transform-es2015-literals@6.0.14, babel-plugin-transform-es2015-typeof-symbol@6.0.14, babel-plugin-transform-es2015-arrow-functions@6.0.14, babel-plugin-transform-es2015-spread@6.0.14, babel-plugin-transform-es2015-classes@6.0.14, babel-plugin-transform-es2015-block-scoping@6.0.14, babel-plugin-transform-es2015-parameters@6.0.14, babel-plugin-transform-regenerator@6.0.14, babel-plugin-transform-es2015-function-name@6.0.14, babel-plugin-transform-es2015-modules-commonjs@6.0.14, babel-plugin-transform-es2015-sticky-regex@6.0.14, babel-plugin-transform-es2015-shorthand-properties@6.0.14, babel-plugin-transform-es2015-object-super@6.0.14, babel-plugin-transform-es2015-unicode-regex@6.0.14, babel-plugin-transform-es2015-computed-properties@6.0.14)

undertaker-lib-tasks@0.5.1 node_modules/undertaker-lib-tasks
├── undertaker-registry@0.0.3
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── export-files@2.1.0 (lazy-cache@0.1.0)
├── merge-stream@1.0.0 (readable-stream@2.0.3)
├── vinyl-fs@2.2.1 (is-valid-glob@0.3.0, object-assign@4.0.1, graceful-fs@4.1.2, strip-bom-stream@1.0.0, strip-bom@2.0.0, through2-filter@2.0.0, vinyl@1.1.0, gulp-sourcemaps@1.6.0, mkdirp@0.5.1, duplexify@3.4.2, glob-stream@5.0.0)
├── resolve-require@0.2.0 (tildify@1.1.2, resolve@1.1.6, cwd@0.6.0)
├── lodash@3.10.1
├── gulp-if@2.0.0 (gulp-match@1.0.0, ternary-stream@2.0.0)
├── gulp-watch@4.3.5 (path-is-absolute@1.0.0, glob2base@0.0.12, vinyl@0.5.3, readable-stream@2.0.3, vinyl-file@1.2.1, glob@5.0.15, anymatch@1.3.0, chokidar@1.2.0)
└── browser-sync@2.9.11 (ucfirst@1.0.0, async-each-series@0.1.1, longest@1.0.1, emitter-steward@1.0.0, dev-ip@1.0.1, immutable@3.7.5, ua-parser-js@0.7.9, pad-left@2.0.0, query-string@2.4.2, opn@3.0.2, browser-sync-client@2.3.4, portscanner@1.0.0, easy-extender@2.3.1, connect@3.4.0, serve-static@1.10.0, resp-modifier@5.0.2, eazy-logger@2.1.2, meow@3.3.0, foxy@11.1.3, anymatch@1.3.0, serve-index@1.7.2, localtunnel@1.7.0, socket.io@1.3.7, browser-sync-ui@0.5.16, chokidar@1.2.0)
λ /tmp/angular-strap @master
$ lgulp build
[01:01:48] Found 1 undertaker-registry to load with ng-factory
[01:01:48] Using ng-factory config file /private/tmp/angular-strap/ngfactory.json
[01:01:49] Using gulpfile /private/tmp/angular-strap/gulpfile.js
[01:01:49] Starting 'default'...
[01:01:49] Starting 'ng:build'...
[01:01:49] Starting 'ng:dist/clean'...
[01:01:49] Finished 'ng:dist/clean' after 25 ms
[01:01:49] Starting 'parallel'...
[01:01:49] Starting 'ng:dist/templates'...
[01:01:49] Starting 'ng:dist/scripts'...
[01:01:49] Starting 'ng:dist/styles'...
[01:01:52] Finished 'ng:dist/styles' after 3.12 s
[01:01:55] Finished 'ng:dist/templates' after 5.99 s
[01:01:56] Finished 'ng:dist/scripts' after 7.16 s
[01:01:56] Finished 'parallel' after 7.16 s
[01:01:56] Finished 'ng:build' after 7.19 s
[01:01:56] Starting 'compat'...
[01:01:57] Finished 'compat' after 614 ms
[01:01:57] Starting 'afterBuild'...
[01:01:57] Finished 'afterBuild' after 3.23 ms
[01:01:57] Finished 'default' after 7.81 s
```

**Comment by austin-bittinger** [comment]
@mgcrea Which version of npm are you using? Trying to build this on Windows and gulp-pre dies trying to use ```ln```. I'm assuming from your shell that you're on a UNIX-like, but I'd be curious about what exactly your setup is
