### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by haddouti-khalid** [mgcrea/angular-strap#2111]
I clone the angular-starp repository and I have a problem with the command **npm install** :

```
293219 verbose lifecycle node-sass@3.4.2~postinstall: CWD: C:\Users\khaddouti\Desktop\git-repo\angular-strap\node_modules\factory-angular-channels\node_modules\gulp-sass\node_modules\node-sass
293220 silly lifecycle node-sass@3.4.2~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
293221 silly lifecycle node-sass@3.4.2~postinstall: Returned: code: 1  signal: null
293222 info lifecycle node-sass@3.4.2~postinstall: Failed to exec postinstall script
293223 verbose unlock done using C:\Users\khaddouti\AppData\Roaming\npm-cache\_locks\staging-22ec9ed51f375fa7.lock for C:\Users\khaddouti\Desktop\git-repo\angular-strap\node_modules\.staging
293224 silly rollbackFailedOptional Starting
293225 silly rollbackFailedOptional Finishing
293226 silly runTopLevelLifecycles Starting
293227 silly runTopLevelLifecycles Finishing
293228 silly install printInstalled
293229 warn optional Skipping failed optional dependency /chokidar/fsevents:
293230 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
293231 warn optional Skipping failed optional dependency /undertaker-lib-tasks/browser-sync/chokidar/fsevents:
293232 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
293233 warn optional Skipping failed optional dependency /undertaker-lib-tasks/gulp-watch/chokidar/fsevents:
293234 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
293235 warn eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none was installed.
293236 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
293236 verbose stack Exit status 1
293236 verbose stack     at EventEmitter.<anonymous> (C:\Users\khaddouti\AppData\Roaming\nvm\v6.2.0\node_modules\npm\lib\utils\lifecycle.js:245:16)
293236 verbose stack     at emitTwo (events.js:106:13)
293236 verbose stack     at EventEmitter.emit (events.js:191:7)
293236 verbose stack     at ChildProcess.<anonymous> (C:\Users\khaddouti\AppData\Roaming\nvm\v6.2.0\node_modules\npm\lib\utils\spawn.js:24:14)
293236 verbose stack     at emitTwo (events.js:106:13)
293236 verbose stack     at ChildProcess.emit (events.js:191:7)
293236 verbose stack     at maybeClose (internal/child_process.js:850:16)
293236 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
293237 verbose pkgid node-sass@3.4.2
293238 verbose cwd C:\Users\khaddouti\Desktop\git-repo\angular-strap
293239 error Windows_NT 6.1.7601
293240 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
293241 error node v6.2.0
293242 error npm  v3.8.9
293243 error code ELIFECYCLE
293244 error node-sass@3.4.2 postinstall: `node scripts/build.js`
293244 error Exit status 1
293245 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
293245 error Make sure you have the latest version of node.js and npm installed.
293245 error If you do, this is most likely a problem with the node-sass package,
293245 error not with npm itself.
293245 error Tell the author that this fails on your system:
293245 error     node scripts/build.js
293245 error You can get information on how to open an issue for this project with:
293245 error     npm bugs node-sass
293245 error Or if that isn't available, you can get their info via:
293245 error     npm owner ls node-sass
293245 error There is likely additional logging output above.
293246 verbose exit [ 1, true ]
```

I note that I use the last version of **npm 3.8.9**.

Thank you ^*

**Comment by DaleWebb** [comment]
I think this is an issue with node-sass.  You should raise the issue there.
