### ISSUE TITLE
Modal Problem

### ISSUE THREAD

**Issue by mmt78** [mgcrea/angular-strap#2220]
TypeError: Cannot set property 'zIndex' of undefined
    at css (http://localhost:8888/kiraTakip/admin/js/vendor/angular/angular.min.js:189:32)
    at U.(anonymous function) [as css] (http://localhost:8888/kiraTakip/admin/js/vendor/angular/angular.min.js:190:498)
    at x.show (http://cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.12/angular-strap.min.js:9:11476)

When trying to open a modal windows, I get this error. Could you help me please?

**Comment by kodero** [comment]
Yeah, also experiencing the same problem but on 
`<button bs-modal template="template.html">`

Can't get it to work. Any workaround?
